## Base logger properties, basically just saying what level to log and where
rootLogger.level=info
rootLogger.appenderRefs=console
rootLogger.appenderRef.console.ref=ConsoleAppender
appender.console.type=Console
appender.console.name=ConsoleAppender
appender.console.target=SYSTEM_OUT

# defines root logger layout, so how the logger actually formats things
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=%d{HH:mm:ss} %-5level %c - %msg%n



## Audit logger properties, what we actually are using for audit logs
# strategy ones are controlling number of rollover files, policies.size are file sizes for the logs
appender.audit.type=RollingFile
appender.audit.name=AuditFile
appender.audit.fileName=logs/system_logs_0.log
appender.audit.filePattern=logs/system_logs_%i.log
appender.audit.layout.type=PatternLayout
appender.audit.layout.pattern=%c %msg%n

appender.audit.policies.type=Policies
appender.audit.policies.size.type=SizeBasedTriggeringPolicy
appender.audit.policies.size.size=600b


# max seems to be max number of backup files, so 9 + 1 active log file
appender.audit.strategy.type=DefaultRolloverStrategy
appender.audit.strategy.min=1
appender.audit.strategy.max=9
appender.audit.strategy.fileIndex=min



logger.audit.name=AUDIT
logger.audit.level=info
logger.audit.additivity=false
logger.audit.appenderRefs=audit
logger.audit.appenderRef.audit.ref=AuditFile